#!/bin/sh

# Branch checkout warning
if [ "$3" = "1" ]; then
  BRANCH=$(git branch --show-current)
  if [ "$BRANCH" = "main" ]; then
    echo "====================================="
    echo "[WARNING] Switching to MAIN branch."
    echo "MAIN is read-only (merge only)."
    echo "====================================="
  fi
fi

exit 0